### ISSUE TITLE
Pre v1.0.0 todo list

### ISSUE THREAD

**Issue by hinto-janai** [hinto-janai/festival#12]
## `CCD`
- [x] Add parent folder `jpg/png` scanning+parsing if no embedded image in audio file

## Data Sanitation Routines
- [x] `Kernel` - `Collection`
- [x] `Kernel` - `KernelState`
- [x] `GUI` - `Settings`
- [x] `GUI` - `State`

## Docs
- [x] Main `README.md`
- [x] Inner `README.md`'s
- [x] `external/`
- [x] `shukusai` code
- [x] `GUI` code

## Visibility check
- [x] `shukusai` pub/priv
- [x] `GUI` pub/priv
- [x] Modules

## `cfg`
- [x] `#[cfg(feature = "frontend-egui")]`

## Dependencies
- [x] Lock in `egui` versions
- [x] Lock in personal library versions
- [x] Fix dependencies for workspace members polluting main `Cargo.toml`

## Misc
- [x] Update `cmp/` (re-evaluate Festival perf)
- [ ] `crates.io` update (shell packages)
- [x] `festival.pm`
- [x] AUR package
